#! Copyright 2021 VMware, Inc.
#! SPDX-License-Identifier: Apache-2.0

#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---
repository: ""
service_account:
  name: ""
  namespace: ""
