#@ load("/values.star", "docker_configjson")
#@ load("@ytt:data", "data")

#@ if data.values.repository_secret.name != "":
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.repository_secret.name
  namespace: #@ data.values.repository_secret.namespace
spec:
  toNamespaces:
    - kpack
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: #@ data.values.repository_secret.name
  namespace: kpack
spec:
  fromNamespace: #@ data.values.repository_secret.namespace
#@ else:
---
apiVersion: v1
kind: Secret
metadata:
  name:  kpack-dependencies-repository-secret
  namespace: kpack
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ docker_configjson
#@ end