#@ load("@ytt:data", "data")

#@ for stack in data.values.stacks:
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: #@ stack.name
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: #@ stack.buildImage
  runImage:
    image: #@ stack.runImage
#@ end